on: [push]

jobs:
  publish_archive_job:
    runs-on: ubuntu-latest
    name: A job to publish Zulip archive in GitHub pages
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run archive
      id: archive
      uses: hackerkid/zulip-archive-action@master
      with:
        site: ${{ secrets.site }}
        key: ${{ secrets.key }}
